kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mlflow-access-rbac
subjects:
  - kind: ServiceAccount
    name: mlflow-access
    namespace: mlflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mlflow-sa-oauth-access
