apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mlflow-sa-oauth-access
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - route.openshift.io
    resources:
      - routes